// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace lcLLM
{
    internal sealed partial class Vsix
    {
        public const string Id = "lcLLM.18763b3e-4e07-42f3-993e-65bea52b8c85";
        public const string Name = "lcLLM";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "HP";
        public const string Tags = "";
    }
}
