// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace lcLLM
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSHLMainMenuString = "d309f791-903f-11d0-9efc-00a0c911004f";
        public static Guid guidSHLMainMenu = new Guid(guidSHLMainMenuString);

        public const string guidlcLLMPackageString = "18763b3e-4e07-42f3-993e-65bea52b8c44";
        public static Guid guidlcLLMPackage = new Guid(guidlcLLMPackageString);

        public const string guidTextEditorString = "8b382828-6202-11d1-8870-0000f87579d2";
        public static Guid guidTextEditor = new Guid(guidTextEditorString);

        public const string lcLLMCommandString = "714b6862-aad7-434e-8415-dd928555ba02";
        public static Guid lcLLMCommand = new Guid(lcLLMCommandString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MainLcMenu = 0x1020;
        public const int MainMenuGroup = 0x1021;
        public const int cmdRequestRefactor = 0x00FA;
        public const int cmdGenerateUnitTests = 0x00FB;
        public const int cmdDocumentCode = 0x00FC;
        public const int cmdCodeReview = 0x00FD;
        public const int cmdManualPrompt = 0x00FE;
    }
}
