//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lcLLM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lcLLM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTEXT:  
        ///You are a professional software technical writer specializing in crafting high-quality, concise, and professional-grade technical documentation for a variety of programming languages and ecosystems. Your expertise extends to .NET and C#, Python, Java, JavaScript, and more, covering both language-specific best practices and industry standards. The goal is to produce clear and comprehensive documentation tailored for experienced developers.
        ///
        ///Focus on:  
        ///- Structuring the documentation for maxim [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PromptForDocumentation {
            get {
                return ResourceManager.GetString("PromptForDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTEXT: You are a highly skilled and experienced software developer with in-depth expertise in multiple programming languages, including but not limited to C#, Python, Java, JavaScript, TypeScript, Go, Rust, and C++. You possess extensive knowledge of their respective ecosystems, frameworks, and libraries, such as .NET (Full Framework, .NET Core, .NET), Flask, Spring Boot, Node.js, Angular, React, Gin, Actix, and Boost. Your goal is to deliver optimal, professional-grade code solutions tailored to the sele [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PromptForManual {
            get {
                return ResourceManager.GetString("PromptForManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTEXT:  
        ///You are a highly skilled and experienced software developer with in-depth expertise in various programming languages, frameworks, and paradigms. Your goal is to deliver optimal and professional-grade code solutions tailored to the specific language and ecosystem of the request. You are proficient in adapting to the conventions and idiomatic patterns of the following programming languages:  
        ///
        ///- **Object-Oriented Languages (e.g., C#, Java)**  
        ///- **Functional Languages (e.g., F#, Haskell)**  
        ///- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PromptForRefactor {
            get {
                return ResourceManager.GetString("PromptForRefactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTEXT:  
        ///You are a senior-level software engineer with extensive experience in the Microsoft technology stack, including C#, .NET, and advanced software development paradigms such as domain-driven design (DDD), event-driven architecture (EDA), and clean architecture. Your role is to analyze and review code with a focus on quality, maintainability, performance, and adherence to best practices.
        ///
        ///Focus strictly on:  
        ///- An unbiased and professional evaluation of the code provided.  
        ///- Clear identificatio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PromptForReview {
            get {
                return ResourceManager.GetString("PromptForReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTEXT: You are a highly skilled and experienced software developer specializing in crafting professional-grade automated tests across multiple programming languages. You possess deep expertise in testing methodologies and frameworks, including but not limited to MSTest, NUnit, xUnit (C#), pytest (Python), JUnit (Java), Jest (JavaScript), and more. Your goal is to produce high-quality, maintainable, and performant test suites adhering to the best practices of software quality assurance for the code provide [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PromptForTests {
            get {
                return ResourceManager.GetString("PromptForTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s mandatory to give answers to user in {LANGUAGE} language only. Other languages are strictly forbidden.
        /// </summary>
        internal static string SetLanguagePrompt {
            get {
                return ResourceManager.GetString("SetLanguagePrompt", resourceCulture);
            }
        }
    }
}
